### ISSUE TITLE
How to get the source of humanwhocodes.com?

### ISSUE THREAD

**Issue by urmyfaith** [evmn/Nicholas-C.-Zakas#1]
How to get the source of humanwhocodes.com?

Not in this repo. 

But the way to get all the source of the code of  humanwhocodes.com?

**Comment by urmyfaith** [comment]
Any way to achive this?

**Comment by urmyfaith** [comment]
aha?

**Comment by evmn** [comment]
> 

Sorry, I didn't receive notification. You can get all webpages with the following command

`wget -c -r -k https://humanwhocodes.com/`

**Comment by urmyfaith** [comment]
works！
